#pragma once

#include <string>

enum class Tag {
    ASSIGNMENT,
    ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION, EXPONENTIATION, MODULO,
    GREATER_THAN, LESS_THAN, GREATER_THAN_OR_EQUAL, LESS_THAN_OR_EQUAL, EQUAL, NOT_EQUAL,
    AND, OR, NOT, COMMA, IDENTIFIER,
    TRUE, FALSE,
    OPEN_PARENTHESES, CLOSE_PARENTHESES, NEWLINE,
    UNKNOWN,
    INTEGER_LITERAL, BOOLEAN_LITERAL,
};

std::string enumTagToString(Tag tag);   